apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nec.msbu.core.web
  name: nec.msbu.core.web
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nec.msbu.core.web
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
       app: nec.msbu.core.web
    spec:
      containers:
      - env:
        - name: API_HOST
          value: https://172.26.67.36
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: crypticpassword
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /https/aspnetapp.pfx
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+80
        image: frickson/necmsbucoreweb
        name: nec.msbu.core.web
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
   app: nec.msbu.core.web
  name: nec.msbu.core.web
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    app: nec.msbu.core.web
  type: LoadBalancer
