apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   app: webservice
  name: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
       app: webservice
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: crypticpassword
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /https/aspnetapp.pfx
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+80
        image: frickson/necmsbucorewebservice
        name: webservice
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}


---

apiVersion: v1
kind: Service
metadata:
  labels:
   app: webservice
  name: webservice
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
   app: webservice
status:
  loadBalancer: {}
